In [2]:
import pandas as pd
from transformers import pipeline

# 1. Load test Dataset

In [4]:
test_data = pd.read_csv("../data/processed/test_data.csv")

In [62]:
# let's make a copy of it
test_results = test_data.copy()
texts = test_results["text"].tolist()
true_labels = test_results["sentiment"].tolist()
original_indexes = test_results["original_index"].tolist()

# 2. Load pre-trained Model

In [6]:
# Also let's get the predicted_labels and confidence score from the model
# let's load the FinBERT using the pipeline
pipe = pipeline("text-classification", model="ProsusAI/finbert")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

In [34]:
model_pred = pipe(texts, batch_size=32)
pred_labels = [obj['label'] for obj in model_pred]
pred_score = [obj['score'] for obj in model_pred]

# 3. Analysis dataframe 
This dataframe contains columns of text, true_labels and from the model we have pred_labels for model predicted labels and pred_score for the model confidence in the prediction

In [64]:
analysis_obj = {
    "original_index": original_indexes,
    "text" : texts,
    "true_label": true_labels,
    "predicted_label": pred_labels,
    "pred_score": pred_score
}
analysis_df = pd.DataFrame(data=analysis_obj)

In [65]:
analysis_df

,original_index,text,true_label,predicted_label,pred_score
0,2636,"The mill will have capacity to produce 500,000 tonnes of pulp per year .",neutral,neutral,0.841666
1,547,"HELSINKI ( AFX ) - Nokian Tyres reported a fourth quarter pretax profit of 61.5 mln eur , up from 48.6 mln on the back of strong sales .",positive,positive,0.953589
2,4685,The company confirmed its estimate for lower revenue for the whole 2009 than the year-ago EUR93 .9 m as given in the interim report on 5 August 2009 .,negative,negative,0.972156
3,3071,"Prior to the transaction , whose financial terms have not been disclosed , Alma Media owned 40 % of Kotikokki net .",neutral,neutral,0.952597
4,2988,"L+Ænnen Tehtaat 's Food Division was reorganised into two strategic business units , Apetit Frozen Foods and Jams , and Apetit Fish .",neutral,neutral,0.938348
...,...,...,...,...,...
718,4472,"The previously concluded adaptation measures , concerning other staff , were adequate for the time being , and the planning operations continue as before at the plant , the company said .",positive,positive,0.921316
719,4807,"Operating result for the 12-month period decreased from the profit of EUR0 .4 m while turnover decreased from EUR5 .6 m , as compared to 2004 .",negative,negative,0.974548
720,3528,Combined net sales in 2006 were $ 27 million and EBITDA was $ 13.7 million .,neutral,neutral,0.944923
721,4553,"Operating profit for the six-month period decreased from EUR111 .9 m , while sales increased from EUR1 ,275 m , as compared to the corresponding period in 2006 .",neutral,negative,0.973749
722,226,"( ADP News ) - Feb 11 , 2009 - Finnish management software solutions provider Ixonos Oyj ( HEL : XNS1V ) said today its net profit rose to EUR 3.5 million ( USD 4.5 m ) for 2008 from EUR 3.1 million for 2007 .",positive,positive,0.950221

# 4. Error analysis dataframe

In [66]:
# let's check how many of the predictions predict wrong and why
errors_df = analysis_df[
    analysis_df["true_label"] != analysis_df["predicted_label"]
]
errors_df

,original_index,text,true_label,predicted_label,pred_score
17,2166,"Pre-tax loss totaled EUR 0.3 mn , compared to a loss of EUR 2.2 mn in the first quarter of 2005 .",positive,negative,0.593626
24,1536,"In the next few years , the ICT sector 's share of electricity consumption will be raised by the increase in the popularity of smartphones .",neutral,positive,0.845783
33,3778,The company said that it has agreed to a EUR160m unsecured credit line from lenders .,neutral,positive,0.929986
42,222,Its total annual revenue comes up to about 160 mln zloty ( $ 56.9 mln-42 .3 mln euro ) .,neutral,positive,0.800894
86,3169,"The company has decided to stop the operations of Ruukki Construction Division in Latvia and Lithuania , and concentrate the production and logistics in Parnu , Estonia in 2009 .",neutral,negative,0.853950
...,...,...,...,...,...
692,4575,"ASPOCOMP GROUP OYJ STOCK EXCHANGE RELEASE December 15 , 2006 at 4:50 PM According to the disclosure received today by Aspocomp Group Oyj , the share of Henrik Nyberg in Aspocomp Group Oyj 's share capital and votes has decreased below 5 percent .",neutral,negative,0.922802
695,2700,` Nordic infrastructure construction is one of our strategic growth areas .,neutral,positive,0.639643
703,1988,"As a result of the cancellation , the maximum increase of Citycon 's share capital on the basis of the convertible bonds decreased from EUR 23,383,927.80 to EUR 22,901,784.75 .",neutral,negative,0.542261
707,468,`` The sale of the oxygen measurement business strengthens our goal to focus on our chosen market segments .,neutral,positive,0.936913
721,4553,"Operating profit for the six-month period decreased from EUR111 .9 m , while sales increased from EUR1 ,275 m , as compared to the corresponding period in 2006 .",neutral,negative,0.973749

In [67]:
# let's check the distribution
errors_df.groupby(["true_label", "predicted_label"]).size()

true_label  predicted_label
negative    neutral             2
neutral     negative           26
            positive           40
positive    negative            2
            neutral            16
dtype: int64

In [68]:
pd.set_option("display.max_colwidth", None)
# let's check the wrong predictions with highest confidence scores, if any
errors_df.sort_values(
    "pred_score",
    ascending=False
).head(20)

,original_index,text,true_label,predicted_label,pred_score
721,4553,"Operating profit for the six-month period decreased from EUR111 .9 m , while sales increased from EUR1 ,275 m , as compared to the corresponding period in 2006 .",neutral,negative,0.973749
389,59,"In Sweden , Gallerix accumulated SEK denominated sales were down 1 % and EUR denominated sales were up 11 % .",neutral,negative,0.972846
613,2401,"At 10.58 am , Outokumpu declined 2.74 pct to 24.87 eur , while the OMX Helsinki 25 was 0.55 pct higher at 2,825.14 and the OMX Helsinki added 0.64 pct to 9,386.89 .",neutral,negative,0.951658
342,4464,The board further said the company omitted to tender for a substantial part of the works and as such they had rightfully been found non-responsive by the evaluation team .,neutral,negative,0.942037
137,2451,"firm 28 October 2009 - Finnish lifting equipment maker Konecranes Oyj HEL : KCR1V said today it acquired US Machine Tool Solutions Unlimited in Cincinnati , Ohio , for an undisclosed sum .",positive,neutral,0.938728
707,468,`` The sale of the oxygen measurement business strengthens our goal to focus on our chosen market segments .,neutral,positive,0.936913
453,3186,"The company will also shut one paper machine in Finland and one in Austria , as well as two label paper machines in Finland for up to 10 months , Helsinki-based UPM said yesterday .",neutral,negative,0.934186
649,949,Finnish mobile operator DNA will function as a subcontractor to Maingate and will be responsible for telecommunications connections .,positive,neutral,0.930086
33,3778,The company said that it has agreed to a EUR160m unsecured credit line from lenders .,neutral,positive,0.929986
372,1585,s already good position in the technical building services market in Ostrobothnia .,neutral,positive,0.928239
410,4197,Nokia is requesting that the companies stop making and selling the mobile phones and pay monetary damages and costs .,neutral,negative,0.922890
692,4575,"ASPOCOMP GROUP OYJ STOCK EXCHANGE RELEASE December 15 , 2006 at 4:50 PM According to the disclosure received today by Aspocomp Group Oyj , the share of Henrik Nyberg in Aspocomp Group Oyj 's share capital and votes has decreased below 5 percent .",neutral,negative,0.922802
640,779,Stora Enso owns 43 percent of Bergvik and earns therefore SEK 1.5 bn on the value appreciation .,positive,neutral,0.921838
314,3213,The duration of the lay-offs per employee will vary from one to six weeks .,neutral,negative,0.917564
159,3310,The prices of stainless steel also rose in Europe .,neutral,positive,0.909573
334,4451,"I use natural fibers to make the clothes more comfortable , to allow your skin to breathe and to be eco-friendly .",positive,neutral,0.901556
689,1209,"Employees are also better prepared to answer calls , since they already have detailed information about the caller before they answer the phone . ''",positive,neutral,0.901056
574,510,The company plans to spend the proceeds from the rights offering for strengthening its balance sheet .,neutral,positive,0.900021
343,850,"In addition , Lehdentekijat Oy will start producing a new membership magazine , Viisas Raha ( Wise Money ) for the Association .",positive,neutral,0.898201
638,414,A tinyurl link takes users to a scamming site promising that users can earn thousands of dollars by becoming a Google ( NASDAQ : GOOG ) Cash advertiser .,negative,neutral,0.893416

In [79]:
# Now from the analysis, neutral -> positive prediction is the highest, let's inspect them
neutral_positive_errors = errors_df[
    (errors_df["true_label"] == "neutral") & (errors_df["predicted_label"] == "positive")
]
neutral_positive_errors

,original_index,text,true_label,predicted_label,pred_score
24,1536,"In the next few years , the ICT sector 's share of electricity consumption will be raised by the increase in the popularity of smartphones .",neutral,positive,0.845783
33,3778,The company said that it has agreed to a EUR160m unsecured credit line from lenders .,neutral,positive,0.929986
42,222,Its total annual revenue comes up to about 160 mln zloty ( $ 56.9 mln-42 .3 mln euro ) .,neutral,positive,0.800894
102,3272,The new location is n't the only change Wellmont has in store for its air transport service .,neutral,positive,0.602828
159,3310,The prices of stainless steel also rose in Europe .,neutral,positive,0.909573
173,1480,"3G data subscribers are also helping to maintain these growth levels , since data-only subscriptions push for more multiple SIM ownership .",neutral,positive,0.888020
178,3945,"Vacon aims to establish its presence in the solar energy business in various parts of the world towards the end of 2010 , said Olli Teva , marketing director renewable energy applications .",neutral,positive,0.823138
184,1746,"Mr. Atul Chopra , Chief Operating Officer & President , Tecnotree elaborated '' I am eager to see the continued success of the former Tecnomen , bringing Lifetree product to MENA , under the Tecnotree umbrella .",neutral,positive,0.849241
242,2976,Joint procurement will be later extended to the factories in the Baltic countries .,neutral,positive,0.696376
252,1854,"So far the company has awarded more than $ 350,000 worth of tools and materials .",neutral,positive,0.676479
255,3995,He said : `` It is for sale again and we will be actively marketing it .,neutral,positive,0.802696
291,458,TietoEnator signed an agreement to acquire Indian research and development ( R&D ) services provider and turnkey software solutions developer Fortuna Technologies Pvt. Ltd. for 21 mln euro ( $ 30.3 mln ) in September 2007 .,neutral,positive,0.753397
297,396,Finnish Talvivaara Mining Co HEL : TLV1V said Thursday it had picked BofA Merrill Lynch and JPMorgan NYSE : JPM as joint bookrunners of its planned issue of convertible notes worth up to EUR250m USD332m .,neutral,positive,0.719229
298,2273,Glaston also has efficiency measures in all other units .,neutral,positive,0.569529
315,4493,"Amer , which bought Salomon from adidas in October , said the job cuts are aimed at boosting competitiveness .",neutral,positive,0.886473
325,2447,"Finnish metal components supplier Componenta on December 26 , 2006 applied for approval with the Turkish Capital Markets Board to launch a mandatory offer for the remaining shares in iron and aluminium castings producer Doktas Dokumculuk .",neutral,positive,0.591089
340,3571,"Following the issue , the number of shares in the Swedish company will grow by 9 % .",neutral,positive,0.891750
349,505,"The acquisition is part of Suomen Helasto 's strategy to expand the LukkoExpert Security chain , Suomen Helasto CEO Kimmo Uusimaki said .",neutral,positive,0.855178
350,4455,"wins 98 % acceptance 23 December 2009 - Finnish industrial machinery company Metso Oyj ( HEL : MEO1V ) said today it will complete its takeover offer for textile company Tamfelt Oyj Abp ( HEL : TAFKS ) , after acquiring 98 % of its shares and votes .",neutral,positive,0.838734
365,3828,The goal is significant expansion in Finland and in the northern Baltic region .,neutral,positive,0.874518
372,1585,s already good position in the technical building services market in Ostrobothnia .,neutral,positive,0.928239
374,1333,South America and Asia are other promising markets .,neutral,positive,0.604685
390,1511,Elisa will expand the use of this technology provided the pilot proves successful .,neutral,positive,0.842517
403,3765,The company expects its net sales for the whole 2009 to be at previous year levels .,neutral,positive,0.768682
425,3351,"The technology will become available to businesses from the fourth quarter , Nokia said .",neutral,positive,0.504138
444,4780,"Because expenditures must be justified to pass budget approval hurdles , we believe our RoP model can help make it easier for IT and IT security practitioners to make the business case for acquiring enabling security technologies and related control activities .",neutral,positive,0.873448
462,3878,The solution will be installed in the USA to support the North American operations of the customer .,neutral,positive,0.501823
475,3550,Elcoteq expects its net sales for the last quarter of 2010 to be on the level of the third quarter .,neutral,positive,0.772414
574,510,The company plans to spend the proceeds from the rights offering for strengthening its balance sheet .,neutral,positive,0.900021
586,2046,"The report also said Nokia 's operations comprising the sites at Bochum , Ulm , Dusseldorf , Munich and Frankfurt posted operating profit after interest of 246 mln eur .",neutral,positive,0.718370
610,2941,"In terms of power generation , Fortum produced 39.3 TWh of electricity during the first nine months of 2006 , compared with 38.0 TWh during the same period in 2005 , according to figures released in the group 's latest financial results .",neutral,positive,0.745828
619,1711,I thank Jarmo Ukonaho warmly for his contribution and wish him all the best in the future challenges . '',neutral,positive,0.790884
622,3364,The transaction was announced on September 29 when Pohjola Insurance agreed to pay EUR 80 million ( USD 106.3 m ) in cash for Pohjantahti .,neutral,positive,0.562792
656,1949,`` I see my new post as an inspiring challenge .,neutral,positive,0.773806
668,402,The agreement with JM is one in a series of contracts that TeliaSonera has signed in recent months with residential construction and real estate management companies in Sweden .,neutral,positive,0.866488
671,3662,"M-real Corporation Stock Exchange Announcement 29 September 2006 at 4.15 p.m. Kyro Corporation and M-real Corporation , a Metsaliitto Group subsidiary , have agreed on an arrangement which gives M-real option to purchase the Kyroskoski natural gas powerplant from Kyro .",neutral,positive,0.882493
675,399,Pohjola could increase its stake to 45 % in 2013 .,neutral,positive,0.876672
687,1694,Finnish plumbing and heating systems supplier Uponor announced a company-wide cost reduction program in August 2008 .,neutral,positive,0.549748
695,2700,` Nordic infrastructure construction is one of our strategic growth areas .,neutral,positive,0.639643
707,468,`` The sale of the oxygen measurement business strengthens our goal to focus on our chosen market segments .,neutral,positive,0.936913

In [74]:
# among these 40, let's check the top confident score predictions
neutral_positive_errors.sort_values(
    "pred_score",
    ascending=False
).head(20)

,original_index,text,true_label,predicted_label,pred_score
707,468,`` The sale of the oxygen measurement business strengthens our goal to focus on our chosen market segments .,neutral,positive,0.936913
33,3778,The company said that it has agreed to a EUR160m unsecured credit line from lenders .,neutral,positive,0.929986
372,1585,s already good position in the technical building services market in Ostrobothnia .,neutral,positive,0.928239
159,3310,The prices of stainless steel also rose in Europe .,neutral,positive,0.909573
574,510,The company plans to spend the proceeds from the rights offering for strengthening its balance sheet .,neutral,positive,0.900021
340,3571,"Following the issue , the number of shares in the Swedish company will grow by 9 % .",neutral,positive,0.891750
173,1480,"3G data subscribers are also helping to maintain these growth levels , since data-only subscriptions push for more multiple SIM ownership .",neutral,positive,0.888020
315,4493,"Amer , which bought Salomon from adidas in October , said the job cuts are aimed at boosting competitiveness .",neutral,positive,0.886473
671,3662,"M-real Corporation Stock Exchange Announcement 29 September 2006 at 4.15 p.m. Kyro Corporation and M-real Corporation , a Metsaliitto Group subsidiary , have agreed on an arrangement which gives M-real option to purchase the Kyroskoski natural gas powerplant from Kyro .",neutral,positive,0.882493
675,399,Pohjola could increase its stake to 45 % in 2013 .,neutral,positive,0.876672
365,3828,The goal is significant expansion in Finland and in the northern Baltic region .,neutral,positive,0.874518
444,4780,"Because expenditures must be justified to pass budget approval hurdles , we believe our RoP model can help make it easier for IT and IT security practitioners to make the business case for acquiring enabling security technologies and related control activities .",neutral,positive,0.873448
668,402,The agreement with JM is one in a series of contracts that TeliaSonera has signed in recent months with residential construction and real estate management companies in Sweden .,neutral,positive,0.866488
349,505,"The acquisition is part of Suomen Helasto 's strategy to expand the LukkoExpert Security chain , Suomen Helasto CEO Kimmo Uusimaki said .",neutral,positive,0.855178
184,1746,"Mr. Atul Chopra , Chief Operating Officer & President , Tecnotree elaborated '' I am eager to see the continued success of the former Tecnomen , bringing Lifetree product to MENA , under the Tecnotree umbrella .",neutral,positive,0.849241
24,1536,"In the next few years , the ICT sector 's share of electricity consumption will be raised by the increase in the popularity of smartphones .",neutral,positive,0.845783
390,1511,Elisa will expand the use of this technology provided the pilot proves successful .,neutral,positive,0.842517
350,4455,"wins 98 % acceptance 23 December 2009 - Finnish industrial machinery company Metso Oyj ( HEL : MEO1V ) said today it will complete its takeover offer for textile company Tamfelt Oyj Abp ( HEL : TAFKS ) , after acquiring 98 % of its shares and votes .",neutral,positive,0.838734
178,3945,"Vacon aims to establish its presence in the solar energy business in various parts of the world towards the end of 2010 , said Olli Teva , marketing director renewable energy applications .",neutral,positive,0.823138
255,3995,He said : `` It is for sale again and we will be actively marketing it .,neutral,positive,0.802696

In [78]:
# Now in the same way let's check  neutral -> negative predictions, let's inspect them
neutral_negative_errors  = errors_df[
    (errors_df["true_label"] == "neutral") & ((errors_df["predicted_label"] == "negative"))
]
neutral_negative_errors.sort_values(
    "pred_score",
    ascending=False
).head(13)

,original_index,text,true_label,predicted_label,pred_score
721,4553,"Operating profit for the six-month period decreased from EUR111 .9 m , while sales increased from EUR1 ,275 m , as compared to the corresponding period in 2006 .",neutral,negative,0.973749
389,59,"In Sweden , Gallerix accumulated SEK denominated sales were down 1 % and EUR denominated sales were up 11 % .",neutral,negative,0.972846
613,2401,"At 10.58 am , Outokumpu declined 2.74 pct to 24.87 eur , while the OMX Helsinki 25 was 0.55 pct higher at 2,825.14 and the OMX Helsinki added 0.64 pct to 9,386.89 .",neutral,negative,0.951658
342,4464,The board further said the company omitted to tender for a substantial part of the works and as such they had rightfully been found non-responsive by the evaluation team .,neutral,negative,0.942037
453,3186,"The company will also shut one paper machine in Finland and one in Austria , as well as two label paper machines in Finland for up to 10 months , Helsinki-based UPM said yesterday .",neutral,negative,0.934186
410,4197,Nokia is requesting that the companies stop making and selling the mobile phones and pay monetary damages and costs .,neutral,negative,0.922890
692,4575,"ASPOCOMP GROUP OYJ STOCK EXCHANGE RELEASE December 15 , 2006 at 4:50 PM According to the disclosure received today by Aspocomp Group Oyj , the share of Henrik Nyberg in Aspocomp Group Oyj 's share capital and votes has decreased below 5 percent .",neutral,negative,0.922802
314,3213,The duration of the lay-offs per employee will vary from one to six weeks .,neutral,negative,0.917564
552,4086,During the negotiations a reduction of 21 persons has taken place through natural redundancy or termination of fixed-term contracts .,neutral,negative,0.869382
86,3169,"The company has decided to stop the operations of Ruukki Construction Division in Latvia and Lithuania , and concentrate the production and logistics in Parnu , Estonia in 2009 .",neutral,negative,0.853950
129,2903,"F-Secure reported that : - The first half of 2008 has seen a growing number of targeted malware attacks on individuals , companies , and organizations .",neutral,negative,0.786230
608,4105,"The effect may remain short-lived , however .",neutral,negative,0.757467
386,2696,"JVC will stop producing DVD players in Brazil : JVC do Brazil , a subsidiary of Japan 's JVC group announced it will stop the production of DVD players in Brazil .",neutral,negative,0.750131

# Observation
FinBERT reduced keyword-driven errors observed in the classical baseline. Remaining errors were primarily neutral sentences containing positive or negative financial events, suggesting annotation ambiguity rather than lack of domain understanding